GET http://localhost:3000/photos


###
POST http://localhost:3000/photos
Content-Type: application/json

{
    "url": "https://as2.ftcdn.net/v2/jpg/02/64/15/41/1000_F_264154131_XvpBI5fARjB7Qlo4PMrMMTaunXha47NR.jpg",
    "user": "440DC52A-0E27-EE11-9DD3-2839268CD12C"
}

###
POST http://localhost:3000/photos/pagination
Content-Type: application/json

{
    "page": 4,
    "limit": 10
}