GET http://localhost:4000/photos


###
POST http://localhost:4000/photos
Content-Type: application/json

{
    "url": "https://as2.ftcdn.net/v2/jpg/02/64/15/41/1000_F_264154131_XvpBI5fARjB7Qlo4PMrMMTaunXha47NR.jpg",
    "user": "ABB0733E-BF0D-EE11-8DC4-2839268CD12C",
    "fromDate": "2023-06-18"
}