GET http://localhost:5000/users


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Tran Dung"
}


###
POST http://localhost:5000/users/pagination
Content-Type: application/json

{
    "page": 1,
    "limit": 10
}