version: '3.5'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nodejs-container
        ports:
            - '4000:4000'
        volumes:
            - './src:/app/src'
            - /app/node_modules
        networks:
            - trandung
    nginx:
        build:
            context: ./nginx
        container_name: nginx-container
        hostname: nginx
        ports:
            - '5000:5000'
        depends_on:
            - app
        networks:
            - trandung

networks:
    trandung:
