POST http://localhost:3000/photo
Content-Type: application/json

{
    "url": "https://static.vecteezy.com/system/resources/previews/004/218/321/non_2x/cute-cat-white-pet-cartoon-character-free-vector.jpg",
    "user": "64925960b9e050d6db8e48b5"
}

###
GET  http://localhost:3000/photo


###
GET  http://localhost:3000/photo/6491c6d55509f22054bd4f4f